### ISSUE TITLE
Duplicate ihs elements in spm/values.yaml

### ISSUE THREAD

**Issue by meathead23** [IBM/spm-kubernetes#15]
**Describe the bug**
In SPM Umbrella chart under `helm-charts/spm/values.yaml` the `ihs` element is set twice with similar keys present

```
  ihs:
    runAs: 1000
    replicaCount: 1
    readinessPath: /CuramStatic
    ingressPath: /CuramStatic/*
    resources: {}
```
and further down:

```
  ihs:
    serviceType: NodePort
    config:
      readinessPath: /CuramStatic
      ingressPath: /CuramStatic/*
```

This is slightly confusing and the second sections `ingressPath` element isn't picked up by the ingress.yaml template:

```
          - path: {{ .Values.global.ihs.ingressPath | default "/CuramStatic" }}
            backend:
              serviceName: {{ $.Release.Name }}-ihs
              servicePort: http
```
