### ISSUE TITLE
Missing Batch debug-file configmap

### ISSUE THREAD

**Issue by meathead23** [IBM/spm-kubernetes#29]
Issue:

The batch pod no longer starts with the following error: 

`MountVolume.SetUp failed for volume "debug-file" : configmap "spm-dev01-debug" not found`

The `batch/templates/cronjob.yaml` file references `{{ $.Release.Name }}-debug` per:

```yaml
            - name: debug-file
              configMap:
                name: {{ $.Release.Name }}-debug
```

However there doesn't seem to be a confiqmap-debug.yaml file or anything in the project for that volume to reference.
